const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const { query } = require('../db');

// GET /api/sessions/:id/pdf?store=Tukkuguda
router.get('/:id/pdf', async (req, res) => {
  try {
    const { rows: sessions } = await query('SELECT * FROM dispatch_sessions WHERE id=$1', [req.params.id]);
    if (!sessions.length) return res.status(404).json({ error: 'Session not found' });
    const session = sessions[0];

    const store = req.query.store;
    let entriesQuery = 'SELECT * FROM dispatch_entries WHERE session_id=$1 ORDER BY item_name ASC';
    let params = [req.params.id];

    if (store) {
      entriesQuery = 'SELECT * FROM dispatch_entries WHERE session_id=$1 AND destination=$2 ORDER BY item_name ASC';
      params = [req.params.id, store];
    }

    const { rows: entries } = await query(entriesQuery, params);
    if (!entries.length) return res.status(404).json({ error: 'No entries found for this store' });

    const date = new Date(session.session_date).toLocaleDateString('en-IN', {
      day: '2-digit', month: '2-digit', year: 'numeric', timeZone: 'Asia/Kolkata'
    });
    const storeName = store || 'All Stores';
    const filename = `dispatch-${date.replace(/\//g, '-')}-${storeName.replace(/\s/g, '_')}.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    doc.pipe(res);

    // ── Header ──
    doc.fontSize(20).font('Helvetica-Bold').fillColor('#92400e').text('KRISPIES BAKERY', { align: 'center' });
    doc.fontSize(12).font('Helvetica').fillColor('#555').text('Dispatch Delivery Note', { align: 'center' });
    doc.moveDown(0.5);

    // ── Meta box ──
    doc.roundedRect(50, doc.y, 495, 70, 6).fillAndStroke('#fffbeb', '#f59e0b');
    const boxTop = doc.y + 10;
    doc.fillColor('#1c1917').fontSize(11).font('Helvetica-Bold');
    doc.text(`Date:`, 65, boxTop).text(`Store:`, 65, boxTop + 22).text(`Supervisor:`, 65, boxTop + 44);
    doc.font('Helvetica');
    doc.text(date, 160, boxTop).text(storeName, 160, boxTop + 22).text(session.supervisor_name || '—', 160, boxTop + 44);
    doc.moveDown(4.5);

    // ── Table header ──
    const tableTop = doc.y + 4;
    const cols = { no: 50, item: 80, qty: 360, unit: 410, note: 460 };
    doc.rect(50, tableTop, 495, 22).fill('#f59e0b');
    doc.fillColor('white').fontSize(10).font('Helvetica-Bold');
    doc.text('#',         cols.no,   tableTop + 6);
    doc.text('Item Name', cols.item, tableTop + 6);
    doc.text('Qty',       cols.qty,  tableTop + 6, { width: 45, align: 'right' });
    doc.text('Unit',      cols.unit, tableTop + 6);
    doc.text('Note',      cols.note, tableTop + 6);

    // ── Table rows ──
    let y = tableTop + 22;
    entries.forEach((e, i) => {
      const bg = i % 2 === 0 ? '#ffffff' : '#fef3c7';
      doc.rect(50, y, 495, 20).fill(bg);
      doc.fillColor('#1c1917').fontSize(10).font('Helvetica');
      doc.text(String(i + 1),       cols.no,   y + 5);
      doc.text(e.item_name || '',   cols.item,  y + 5, { width: 270 });
      doc.text(String(e.qty || ''), cols.qty,   y + 5, { width: 45, align: 'right' });
      doc.text(e.unit || '',        cols.unit,  y + 5);
      doc.text(e.note || '',        cols.note,  y + 5, { width: 80 });
      y += 20;
    });

    // Border around table
    doc.rect(50, tableTop, 495, y - tableTop).stroke('#e5e7eb');

    // ── Totals ──
    doc.moveDown(1.5);
    doc.fontSize(11).font('Helvetica-Bold').fillColor('#92400e')
      .text(`Total items dispatched: ${entries.length}`, { align: 'right' });

    // ── Signature block ──
    doc.moveDown(3);
    const sigY = doc.y;
    // Factory side
    doc.moveTo(60, sigY + 30).lineTo(220, sigY + 30).stroke('#374151');
    doc.fontSize(10).font('Helvetica').fillColor('#374151').text('Dispatched by (Factory)', 60, sigY + 35);
    doc.fontSize(9).fillColor('#9ca3af').text('Signature & Date', 60, sigY + 47);
    // Store side
    doc.moveTo(330, sigY + 30).lineTo(530, sigY + 30).stroke('#374151');
    doc.fontSize(10).font('Helvetica').fillColor('#374151').text('Received by (Store)', 330, sigY + 35);
    doc.fontSize(9).fillColor('#9ca3af').text('Signature & Date', 330, sigY + 47);

    // ── Footer ──
    doc.moveDown(4);
    doc.fontSize(8).fillColor('#9ca3af').font('Helvetica')
      .text(`Generated by Krispies Dispatch System · ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}`, { align: 'center' });

    doc.end();
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: e.message });
  }
});

module.exports = router;
