services:
  - type: web
    name: krispies-dispatch
    env: node
    buildCommand: npm run install-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ACCESS_KEY
        sync: false
      - key: TOKEN_SALT
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: krispies-db
          property: connectionString

databases:
  - name: krispies-db
    plan: free
